version: '3.8'
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: php artisan serve --host=0.0.0.0
    volumes:
      - ./server:/var/www/html
      - /var/www/html/vendor
    env_file:
      - ./server/.env
    ports:
      - 9000:8000
    networks:
      - db
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3307:3307
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

networks:
  db: