version: '3.8'
services:
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/var/www/html
    ports:
      - 9000:80
    env_file:
      - ./server/.env
    networks:
      - db
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3307:3307
    networks:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db

networks:
  db: